### ISSUE TITLE
Add SEO meta tags for the site.

### ISSUE THREAD

**Issue by jlengstorf** [openwhisk/openwhisk.github.io#18]
- [x] Write a title that's SEO-friendly
- [ ] Write a description that's SEO-friendly
- [ ] Add SEO tags for sharing (Google, OpenGraph, Twitter)
- [ ] Request Twitter cards verification

**Comment by krook** [comment]
We need to figure out what tags are still relevant in 2016. To start, we should get at least the title and description for the main page updated, then focus on sub pages.

For discussion:

```
<title>OpenWhisk | A serverless, open source cloud programming platform</title>
<meta name="copyright" content="From Apache?">
<meta name="description" content="OpenWhisk is a serverless, open source cloud platform that executes functions in response to events at any scale, without managing servers.">
<meta name="keywords" content="serverless, cloud, open source, platform, functions"> <!-- May not be relevant or useful -->
<meta name="robots" content="index,follow">
<meta name="DC.title" content="OpenWhisk | A serverless, open source cloud programming platform">
```

**Comment by jlengstorf** [comment]
@krook I'm fairly certain `keywords` is useless these days. I'm also not sure we need `DC.title`, unless there's a special use I'm not aware of.

Here's what I use on my own site, which has done pretty well for me:

``` html
<meta itemprop="name" content="Jason Lengstorf"/>
<meta itemprop="description" content="Jason Lengstorf is an author, a speaker, and a solver of hard problems. He is currently experimenting with permanent travel and remote work."/>
<meta itemprop="image" content="https://lengstorf.com/images/jason-lengstorf.jpg"/>
<script type="application/ld+json">{
  "@context":"http://schema.org",
  "@type": "Person",
  "url": "https://lengstorf.com/",
  "sameAs": ["https://www.facebook.com/jlengstorf","https://instagram.com/jlengstorf","https://plus.google.com/+Lengstorf","https://www.youtube.com/lengstorf","https://twitter.com/jlengstorf"],
  "name": "Jason Lengstorf"
}</script>
<meta property="og:title" content="Jason Lengstorf"/>
<meta property="og:description" content="Jason Lengstorf is an author, a speaker, and a solver of hard problems. He is currently experimenting with permanent travel and remote work."/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://lengstorf.com/"/>
<meta property="og:image" content="https://lengstorf.com/images/jason-lengstorf.jpg"/>
<meta property="og:updated_time" content="2016-09-28T00:00:00Z"/>
<meta property="article:publisher" content="https://www.facebook.com/jlengstorf"/>
<meta property="fb:admins" content="1468448880"/>
<meta name="twitter:card" content="summary_large_image"/>
<meta name="twitter:image" content="https://lengstorf.com/images/jason-lengstorf.jpg"/>
<meta name="twitter:title" content="Jason Lengstorf"/>
<meta name="twitter:description" content="Jason Lengstorf is an author, a speaker, and a solver of hard problems. He is currently experimenting with permanent travel and remote work."/>
<meta name="twitter:site" content="@jlengstorf"/>
```

In a nutshell, that's:

1. JSON-LD for Google
2. A little microformat stuff (also Google)
3. Open Graph tags (Facebook, LinkedIn, etc.)
4. Twitter card tags

I can make it fairly easy to add these on a per-page basis, but mostly we just need to figure out:

1. What should the `<title>` tag say?
2. What image should show when people share this link?
3. What text should show up in previews when this is shared?

**Comment by krook** [comment]
@jlengstorf Excellent. Lots of options to consider for the later SEO pass. 

These are the official trademarked images as of now. Not sure if this changes with Apache: https://github.com/openwhisk/openwhisk/tree/master/docs/images

Title for the home page should be: "Apache OpenWhisk is a serverless, open source cloud platform". Title for sub pages should be "Apache OpenWhisk for Developers", "Apache OpenWhisk Events" etc.

Preview text should be similar to our CTA text on the homepage. What's our character limit?

**Comment by jlengstorf** [comment]
There's not a character limit, but there's a length limit. I've used this tool to sanity check me in the past: http://www.seomofo.com/snippet-optimizer.html

**Comment by jlengstorf** [comment]
There's now support for `seo_title` on all pages. This will be displayed as the title for search results and as the tab title. The `title` is still used as the main page heading.
